Repository Yamato-Security/takajo, pull requests merged in 2023-12, with the labels that each got.

#75 fix: modify mojibake in stdout `timeline-partition-diagnostic`
  src/takajopkg/extractScriptblocks.nim
  src/takajopkg/general.nim
  src/takajopkg/timelinePartitionDiagnostic.nim
Labels: bug

#77 feat: add `extract-ttps` command
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  src/takajo.nim
  src/takajopkg/ttpVisualize.nim
  takajo.nimble
Labels: enhancement

#79 feat: add `ttp-summary` command
  get-mitre-attack-ttps.py
  mitre-attack.json
  src/takajo.nim
  src/takajopkg/ttpSummary.nim
Labels: enhancement

#80 update readme [WIP]
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  screenshots/extract-scriptblocks.png
  screenshots/sysmon-process-tree.png
  screenshots/timeline-logon.png
  screenshots/timeline-suspicious-processes.png
  screenshots/ttp-summary.png
  screenshots/ttp-visualize.png
  src/takajo.nim
Labels: documentation

#82 feat: add `RuleTitle` to`mitre-attack-navigator.json`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajopkg/ttpVisualize.nim
Labels: enhancement
