Repository Yamato-Security/takajo, pull requests merged in 2024-02, with the labels that each got.

#91 feat: add color gradient to ttp-visualize
  src/takajo.nim
  src/takajopkg/ttpVisualize.nim
Labels: enhancement

#100 chg: update GitHub Actions libraries
  .github/workflows/release.yml
Labels: invalid

#98 feat: add `ttp-visualize-sigma` command
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajo.nim
  src/takajopkg/general.nim
  src/takajopkg/ttpVisualizeSigma.nim
  takajo.nimble
Labels: enhancement

#101 feat: add `stack-processes` command
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajo.nim
  src/takajopkg/stackProcesses.nim
Labels: enhancement

#105 feat: add `stack-cmdlines`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajo.nim
  src/takajopkg/stackCmdlines.nim
Labels: enhancement

#106 feat: add `stack-dns`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajo.nim
  src/takajopkg/stackDNS.nim
Labels: enhancement

#102 test: add integration-test for takajo command
  .github/workflows/integration-test.yml
Labels: enhancement

#104 fix: calculate computer column number each execution
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajopkg/splitCsvTimeline.nim
Labels: bug

#108 feat: add `stack-tasks` command
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajo.nim
  src/takajopkg/stackTasks.nim
Labels: enhancement

#107 feat: add `stack-services`
  src/takajo.nim
  src/takajopkg/stackProcesses.nim
  src/takajopkg/stackServices.nim
Labels: enhancement

#111 feat: add `timeline-tasks` command
  .github/workflows/integration-test.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajo.nim
  src/takajopkg/stackTasks.nim
  src/takajopkg/timelineTasks.nim
Labels: enhancement

#113 feat: show alert level for stacking command
  .github/workflows/integration-test.yml
  src/takajo.nim
  src/takajopkg/extractScriptblocks.nim
  src/takajopkg/general.nim
  src/takajopkg/stackCmdlines.nim
  src/takajopkg/stackDNS.nim
  src/takajopkg/stackLogons.nim
  src/takajopkg/stackProcesses.nim
  src/takajopkg/stackServices.nim
  src/takajopkg/stackTasks.nim
  src/takajopkg/stackUtil.nim
  src/takajopkg/takajoTerminal.nim
Labels: enhancement

#114 update readme
  README-Japanese.md
  README.md
Labels: enhancement

#115 finalize 2.4.0
  src/takajo.nim
Labels: enhancement

#117 refactor: remove duplicated codes
  src/takajo.nim
  src/takajopkg/extractScriptblocks.nim
  src/takajopkg/general.nim
  src/takajopkg/listDomains.nim
  src/takajopkg/listHashes.nim
  src/takajopkg/listIpAddresses.nim
  src/takajopkg/splitCsvTimeline.nim
  src/takajopkg/splitJsonTimeline.nim
  src/takajopkg/stackCmdlines.nim
  src/takajopkg/stackDNS.nim
  src/takajopkg/stackLogons.nim
  src/takajopkg/stackProcesses.nim
  src/takajopkg/stackServices.nim
  src/takajopkg/stackTasks.nim
  src/takajopkg/stackUtil.nim
  src/takajopkg/sysmonProcessTree.nim
  src/takajopkg/timelineLogon.nim
  src/takajopkg/timelinePartitionDiagnostic.nim
  src/takajopkg/timelineSuspiciousProcesses.nim
  src/takajopkg/timelineTasks.nim
  src/takajopkg/ttpResult.nim
  src/takajopkg/ttpSummary.nim
  src/takajopkg/ttpVisualize.nim
  src/takajopkg/ttpVisualizeSigma.nim
  src/takajopkg/vtDomainLookup.nim
  src/takajopkg/vtHashLookup.nim
  src/takajopkg/vtIpLookup.nim
  src/takajopkg/vtResult.nim
Labels: enhancement

#118 updated changelog and ver
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajo.nim
  takajo.nimble
Labels: enhancement
