Repository Yamato-Security/takajo, pull requests merged in 2024-03, with the labels that each got.

#124 feat: output numbers with decimal points
  .gitignore
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajopkg/extractScriptblocks.nim
  src/takajopkg/general.nim
  src/takajopkg/listDomains.nim
  src/takajopkg/listHashes.nim
  src/takajopkg/listIpAddresses.nim
  src/takajopkg/listUndetectedEvtxFiles.nim
  src/takajopkg/listUnusedRules.nim
  src/takajopkg/splitCsvTimeline.nim
  src/takajopkg/splitJsonTimeline.nim
  src/takajopkg/stackLogons.nim
  src/takajopkg/stackServices.nim
  src/takajopkg/timelineLogon.nim
  src/takajopkg/timelinePartitionDiagnostic.nim
  src/takajopkg/timelineSuspiciousProcesses.nim
  src/takajopkg/timelineTasks.nim
  src/takajopkg/ttpSummary.nim
  src/takajopkg/ttpVisualize.nim
  src/takajopkg/ttpVisualizeSigma.nim
  src/takajopkg/vtDomainLookup.nim
  src/takajopkg/vtHashLookup.nim
  src/takajopkg/vtIpLookup.nim
Labels: enhancement

#127 feat: add stack-computers command
  .github/workflows/integration-test.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajo.nim
  src/takajopkg/stackComputers.nim
  src/takajopkg/stackUtil.nim
Labels: enhancement

#131 feat: stack-users/stack-ip-addresses
  .github/workflows/integration-test.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajo.nim
  src/takajopkg/stackCmdlines.nim
  src/takajopkg/stackComputers.nim
  src/takajopkg/stackDNS.nim
  src/takajopkg/stackIpAddresses.nim
  src/takajopkg/stackProcesses.nim
  src/takajopkg/stackServices.nim
  src/takajopkg/stackTasks.nim
  src/takajopkg/stackUsers.nim
  src/takajopkg/stackUtil.nim
Labels: enhancement

#135 refactor: apply Template method pattern for automagic command
  .github/workflows/integration-test.yml
  src/takajo.nim
  src/takajopkg/automagic.nim
  src/takajopkg/extractScriptblocks.nim
  src/takajopkg/general.nim
  src/takajopkg/listDomains.nim
  src/takajopkg/listHashes.nim
  src/takajopkg/listIpAddresses.nim
  src/takajopkg/stackCmdlines.nim
  src/takajopkg/stackCommon.nim
  src/takajopkg/stackComputers.nim
  src/takajopkg/stackDNS.nim
  src/takajopkg/stackIpAddresses.nim
  src/takajopkg/stackLogons.nim
  src/takajopkg/stackProcesses.nim
  src/takajopkg/stackServices.nim
  src/takajopkg/stackTasks.nim
  src/takajopkg/stackUsers.nim
  src/takajopkg/takajoCore.nim
  src/takajopkg/timelineLogon.nim
  src/takajopkg/timelinePartitionDiagnostic.nim
  src/takajopkg/timelineSuspiciousProcesses.nim
  src/takajopkg/timelineTasks.nim
  src/takajopkg/ttpSummary.nim
  src/takajopkg/ttpVisualize.nim
Labels: enhancement

#137 added BSidesTokyo badge
  README-Japanese.md
  README.md
Labels: documentation

#138 fix: ttp-visualize/ttp-summary command does not extract count related rule
  src/takajopkg/hayabusaJson.nim
  src/takajopkg/ttpResult.nim
  src/takajopkg/ttpVisualize.nim
  src/takajopkg/ttpVisualizeSigma.nim
Labels: bug

#139 feat: add automagic command
  .github/workflows/integration-test.yml
  src/takajo.nim
  src/takajopkg/automagic.nim
  src/takajopkg/extractScriptblocks.nim
  src/takajopkg/general.nim
  src/takajopkg/listDomains.nim
  src/takajopkg/listHashes.nim
  src/takajopkg/listIpAddresses.nim
  src/takajopkg/stackCmdlines.nim
  src/takajopkg/stackCommon.nim
  src/takajopkg/stackComputers.nim
  src/takajopkg/stackDNS.nim
  src/takajopkg/stackIpAddresses.nim
  src/takajopkg/stackLogons.nim
  src/takajopkg/stackProcesses.nim
  src/takajopkg/stackServices.nim
  src/takajopkg/stackTasks.nim
  src/takajopkg/stackUsers.nim
  src/takajopkg/takajoCore.nim
  src/takajopkg/timelineLogon.nim
  src/takajopkg/timelinePartitionDiagnostic.nim
  src/takajopkg/timelineSuspiciousProcesses.nim
  src/takajopkg/timelineTasks.nim
  src/takajopkg/ttpResult.nim
  src/takajopkg/ttpSummary.nim
  src/takajopkg/ttpVisualize.nim
  src/takajopkg/ttpVisualizeSigma.nim
Labels: enhancement

#144 fix: automagic crash when not verbose profile jsonl
  src/takajopkg/ttpResult.nim
  src/takajopkg/ttpSummary.nim
Labels: bug

#145 Corresponding `timeline` option for directory input
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README.md
  src/takajo.nim
  src/takajopkg/automagic.nim
  src/takajopkg/extractScriptblocks.nim
  src/takajopkg/general.nim
  src/takajopkg/listDomains.nim
  src/takajopkg/listHashes.nim
  src/takajopkg/listIpAddresses.nim
  src/takajopkg/listUndetectedEvtxFiles.nim
  src/takajopkg/listUnusedRules.nim
  src/takajopkg/splitCsvTimeline.nim
  src/takajopkg/splitJsonTimeline.nim
  src/takajopkg/stackCmdlines.nim
  src/takajopkg/stackComputers.nim
  src/takajopkg/stackDNS.nim
  src/takajopkg/stackIpAddresses.nim
  src/takajopkg/stackLogons.nim
  src/takajopkg/stackProcesses.nim
  src/takajopkg/stackServices.nim
  src/takajopkg/stackTasks.nim
  src/takajopkg/stackUsers.nim
  src/takajopkg/sysmonProcessTree.nim
  src/takajopkg/takajoCore.nim
  src/takajopkg/timelineLogon.nim
  src/takajopkg/timelinePartitionDiagnostic.nim
  src/takajopkg/timelineSuspiciousProcesses.nim
  src/takajopkg/timelineTasks.nim
  src/takajopkg/ttpResult.nim
  src/takajopkg/ttpSummary.nim
  src/takajopkg/ttpVisualize.nim
  tests/testsubmodule.nim
Labels: enhancement

#149 doc: update Japanese readme
  README-Japanese.md
  README.md
Labels: documentation
