Repository Yamato-Security/takajo, pull requests merged in 2024-09, with the labels that each got.

#181 Update GitHub Actions setup-nim-action@v2
  .github/workflows/integration-test.yml
  .github/workflows/nim.yml
  .github/workflows/release.yml
Labels: enhancement

#182 #174 fix Consolidate Rules table
  src/takajopkg/htmlReport.nim
  templates/index.template
Labels: enhancement

#185 fix: Release Automation GitHub Actions add copy templates folder
  .github/workflows/release.yml
Labels: bug

#187 fix: add `sqlite3.dll` for windows release binary
  .github/workflows/release.yml
  sqlite3_64.dll
Labels: bug

#189 add detection rule list
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajo.nim
  src/takajopkg/htmlReport.nim
  takajo.nimble
  templates/index.template
Labels: enhancement

#190 fix #176 and graph bug fix
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajopkg/htmlReport.nim
Labels: bug, enhancement
