Repository Yamato-Security/takajo, pull requests merged in 2024-10, with the labels that each got.

#192 feat: add `extract-credentials` command
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/takajo.nim
  src/takajopkg/extractCredentials.nim
  src/takajopkg/takajoCore.nim
Labels: enhancement

#196 chg: use malebolgia to fix compile warning
  src/takajo.nim
  src/takajopkg/vtDomainLookup.nim
  src/takajopkg/vtHashLookup.nim
  src/takajopkg/vtIpLookup.nim
  takajo.nimble
Labels: bug

#202 update 2.7.0 readme
  README-Japanese.md
  README.md
  screenshots/html-server-1-rules-list.png
  screenshots/html-server-2-computer-summary.png
  screenshots/html-server-3-date-filtering.png
  screenshots/html-server-4-rule-filtering.png
  src/takajo.nim
  src/takajopkg/web/htmlServer.nim
Labels: documentation

#205 fix: release automation action's packages name
  .github/workflows/release.yml
Labels: enhancement

#206 fix: rename GitHub action's package name
  .github/workflows/integration-test.yml
Labels: bug

#208 fix: `timeline-logon` output column(`SourceIP` and `SourceComputer`)
  .github/workflows/integration-test.yml
  src/takajopkg/timelineLogon.nim
Labels: bug
